use crate::models::{ContentType, ExportBlock};

#[tauri::command]
pub async fn export_to_markdown(project_name: String, blocks: Vec<ExportBlock>) -> Result<String, String> {
    Ok(render_markdown(&project_name, &blocks))
}

fn type_order() -> &'static [ContentType] {
    &[
        ContentType::Thesis,
        ContentType::Claim,
        ContentType::Question,
        ContentType::Idea,
        ContentType::Task,
        ContentType::Entity,
        ContentType::Definition,
        ContentType::Reference,
        ContentType::Quote,
        ContentType::Opinion,
        ContentType::Reflection,
        ContentType::Narrative,
        ContentType::Comparison,
        ContentType::General,
    ]
}

struct TypeMeta {
    heading: &'static str,
    emoji: &'static str,
}

fn type_meta(t: &ContentType) -> TypeMeta {
    match t {
        ContentType::Thesis => TypeMeta { heading: "Thesis", emoji: "🔬" },
        ContentType::Claim => TypeMeta { heading: "Claims", emoji: "⚡" },
        ContentType::Question => TypeMeta { heading: "Questions", emoji: "❓" },
        ContentType::Idea => TypeMeta { heading: "Ideas", emoji: "💡" },
        ContentType::Task => TypeMeta { heading: "Tasks", emoji: "✅" },
        ContentType::Entity => TypeMeta { heading: "Entities", emoji: "🏷️" },
        ContentType::Definition => TypeMeta { heading: "Definitions", emoji: "📖" },
        ContentType::Reference => TypeMeta { heading: "References", emoji: "🔗" },
        ContentType::Quote => TypeMeta { heading: "Quotes", emoji: "💬" },
        ContentType::Opinion => TypeMeta { heading: "Opinions", emoji: "🗣️" },
        ContentType::Reflection => TypeMeta { heading: "Reflections", emoji: "🪞" },
        ContentType::Narrative => TypeMeta { heading: "Narratives", emoji: "📜" },
        ContentType::Comparison => TypeMeta { heading: "Comparisons", emoji: "⚖️" },
        ContentType::General => TypeMeta { heading: "Notes", emoji: "📝" },
    }
}

fn format_date(ts: Option<i64>) -> String {
    use chrono::{TimeZone, Utc};
    let dt = ts
        .and_then(|t| Utc.timestamp_millis_opt(t).single())
        .unwrap_or_else(Utc::now);
    dt.format("%-d %B %Y").to_string()
}

fn md_cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

fn confidence_bar(c: f64) -> String {
    let pct = (c * 100.0).round() as usize;
    let filled = (c * 5.0).round() as usize;
    let bar = "█".repeat(filled) + &"░".repeat(5 - filled.min(5));
    format!("{} {}%", bar, pct)
}

fn render_markdown(project_name: &str, blocks: &[ExportBlock]) -> String {
    if blocks.is_empty() {
        return format!(
            "# {}\n\n> _No nodes yet._\n\n---\n*Generated by nodepad*",
            project_name
        );
    }

    use std::collections::HashMap;
    let mut by_type: HashMap<String, Vec<&ExportBlock>> = HashMap::new();
    for block in blocks {
        let key = format!("{:?}", block.content_type).to_lowercase();
        by_type.entry(key).or_default().push(block);
    }

    let order = type_order();
    let present_types: Vec<&ContentType> = order
        .iter()
        .filter(|t| {
            let key = format!("{:?}", t).to_lowercase();
            by_type.contains_key(&key)
        })
        .collect();

    let date = format_date(blocks.first().and_then(|b| b.timestamp));
    let pinned_refs: Vec<&ExportBlock> = blocks.iter().filter(|b| b.is_pinned.unwrap_or(false)).collect();

    let mut out = Vec::<String>::new();

    // YAML front matter
    out.push("---".to_string());
    out.push(format!("title: \"{}\"", project_name));
    out.push(format!("date: \"{}\"", date));
    out.push(format!("nodes: {}", blocks.len()));
    out.push(format!(
        "types: [{}]",
        present_types
            .iter()
            .map(|t| format!("\"{}\"", format!("{:?}", t).to_lowercase()))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push("source: nodepad".to_string());
    out.push("---".to_string());
    out.push(String::new());

    // Title
    out.push(format!("# {}", project_name));
    out.push(String::new());
    out.push(format!(
        "> **Generated by nodepad** · {} · {} node{}",
        date,
        blocks.len(),
        if blocks.len() != 1 { "s" } else { "" }
    ));
    out.push(String::new());

    // Stats table
    out.push("## Overview".to_string());
    out.push(String::new());
    out.push("| Type | Count |".to_string());
    out.push("|------|-------|".to_string());
    for t in &present_types {
        let key = format!("{:?}", t).to_lowercase();
        let count = by_type.get(&key).map(|v| v.len()).unwrap_or(0);
        let meta = type_meta(t);
        out.push(format!("| {} {} | {} |", meta.emoji, meta.heading, count));
    }
    out.push(String::new());

    // Pinned section
    if !pinned_refs.is_empty() {
        out.push("## 📌 Pinned".to_string());
        out.push(String::new());
        for block in &pinned_refs {
            out.push(format!("**{}**", md_cell(&block.text)));
            if let Some(ref ann) = block.annotation {
                out.push(format!("> {}", md_cell(ann)));
            }
            out.push(String::new());
        }
    }

    // Sections by type
    for t in &present_types {
        let key = format!("{:?}", t).to_lowercase();
        let type_blocks = match by_type.get(&key) {
            Some(b) => b,
            None => continue,
        };
        let meta = type_meta(t);
        out.push(format!("## {} {}", meta.emoji, meta.heading));
        out.push(String::new());

        match t {
            ContentType::Claim => {
                // Table with confidence
                out.push("| Note | Category | Confidence | Annotation |".to_string());
                out.push("|------|----------|-----------|------------|".to_string());
                for b in type_blocks {
                    let conf = b
                        .confidence
                        .map(|c| confidence_bar(c / 100.0))
                        .unwrap_or_else(|| "—".to_string());
                    let ann = b.annotation.as_deref().unwrap_or("—");
                    let cat = b.category.as_deref().unwrap_or("—");
                    out.push(format!(
                        "| {} | {} | {} | {} |",
                        md_cell(&b.text),
                        md_cell(cat),
                        md_cell(&conf),
                        md_cell(ann)
                    ));
                }
            }
            ContentType::Task => {
                for b in type_blocks {
                    out.push(format!("- [ ] {}", b.text));
                    if let Some(ref ann) = b.annotation {
                        out.push(format!("  > {}", ann));
                    }
                }
            }
            ContentType::Quote => {
                for b in type_blocks {
                    out.push(format!("> {}", b.text));
                    if let Some(ref ann) = b.annotation {
                        out.push(format!(">\n> *{}*", ann));
                    }
                    if let Some(ref cat) = b.category {
                        out.push(format!(">\n> — {}", cat));
                    }
                    out.push(String::new());
                }
            }
            _ => {
                for b in type_blocks {
                    out.push(format!("### {}", b.text));
                    if let Some(ref cat) = b.category {
                        out.push(format!("*{}*", cat));
                        out.push(String::new());
                    }
                    if let Some(ref ann) = b.annotation {
                        out.push(ann.clone());
                        out.push(String::new());
                    }
                    if let Some(ref sources) = b.sources {
                        if !sources.is_empty() {
                            out.push("**Sources:**".to_string());
                            for s in sources {
                                out.push(format!("- [{}]({})", s.title, s.url));
                            }
                            out.push(String::new());
                        }
                    }
                }
            }
        }
        out.push(String::new());
    }

    out.push("---".to_string());
    out.push("*Generated by nodepad*".to_string());

    out.join("\n")
}
